/*
 * SPDX-FileCopyrightText: © 2023 Jinwoo Park (pmnxis@gmail.com)
 *
 * SPDX-License-Identifier: MIT OR Apache-2.0
 */

//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub mod prelude;

pub mod hardware;
